/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-02-18 17:53:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import net.dest.db.DestDAO;
import net.dest.db.DestVO;

public final class DetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("net.dest.db.DestDAO");
    _jspx_imports_classes.add("net.dest.db.DestVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");
DestVO vo = (DestVO) request.getAttribute("dest");
String path = request.getContextPath();
request.setAttribute("dest_img", vo.getDEST_IMG());

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/search_main.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style2.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<title>여행지 상세</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/navbar/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("		<hr class=\"deep_hr\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("			<h3 class=\"view_lable\">\r\n");
      out.write("				<span class=\"rgyBadge\" style=\"font-size: 1.1rem\">");
      out.print(vo.getDEST_COUNTRY());
      out.write("</span>\r\n");
      out.write("				<span id=\"dest_name\">");
      out.print(vo.getDEST_NAME());
      out.write("</span>\r\n");
      out.write("				<div id=\"likebtn\">\r\n");
      out.write("					<a href=\"javascript:;\" class=\"icon2 heart2\"> <img\r\n");
      out.write("						src=\"https://cdn-icons-png.flaticon.com/512/812/812327.png\"\r\n");
      out.write("						alt=\"찜하기\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</h3>\r\n");
      out.write("			<div align=\"center\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				<!-- 					alt=\"destimg\" id=\"dest_img\" width=\"400px\"> -->\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td width=\"40%\"><img src=\"");
      out.print(vo.getDEST_IMG());
      out.write("\"\r\n");
      out.write("							class=\"img-thumbnail\" id=\"dest_img\"\r\n");
      out.write("							alt=\"");
      out.print(vo.getDEST_NAME());
      out.write(" 이미지\" /></td>\r\n");
      out.write("						<td width=\"50%\">\r\n");
      out.write("							<div class=\"content-container\">\r\n");
      out.write("								<h2 class=\"detail-label\">\r\n");
      out.write("									여행지 평점&nbsp;<span class=\"tooltip_custom\">?<span\r\n");
      out.write("										class=\"tooltip-content_custom\">사용자 리뷰를 분석하여 예측한 평점입니다.\r\n");
      out.write("									</span></span>\r\n");
      out.write("								</h2>\r\n");
      out.write("								");
      out.write("\r\n");
      out.write("								<div>\r\n");
      out.write("									<span class=\"position\">비용</span>\r\n");
      out.write("									<progress value=\"");
      out.print(vo.getDEST_MONEY() * 100);
      out.write("\" max=\"100\"\r\n");
      out.write("										id=\"pg\"></progress>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<span class=\"position\">경치</span>\r\n");
      out.write("									<progress value=\"");
      out.print(vo.getDEST_LANDSCAPE() * 100);
      out.write("\" max=\"100\"\r\n");
      out.write("										id=\"pg\"></progress>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<span class=\"position\">재미</span>\r\n");
      out.write("									<progress value=\"");
      out.print(vo.getDEST_FUN() * 100);
      out.write("\" max=\"100\" id=\"pg\"></progress>\r\n");
      out.write("								</div>\r\n");
      out.write("								<br>\r\n");
      out.write("								<h2 class=\"detail-label\">\r\n");
      out.write("									여행지 태그&nbsp;<span class=\"tooltip_custom\">?<span\r\n");
      out.write("										class=\"tooltip-content_custom\">사용자 리뷰에서 자동으로 추출한 태그입니다.\r\n");
      out.write("									</span></span>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<p>\r\n");
      out.write("									");
      out.print(vo.getDEST_TAG());
      out.write("</p>\r\n");
      out.write("								<!-- 								<iframe -->\r\n");
      out.write("								<!-- 								src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13015.197494929274!2d138.7273634!3d35.360625!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6019629a42fdc899%3A0xa6a1fcc916f3a4df!2z7ZuE7KeAIOyCsA!5e0!3m2!1sko!2skr!4v1676183902901!5m2!1sko!2skr\" -->\r\n");
      out.write("								<!-- 								style=\"border: 0;\" allowfullscreen=\"\" loading=\"lazy\" -->\r\n");
      out.write("								<!-- 								referrerpolicy=\"no-referrer-when-downgrade\"></iframe> -->\r\n");
      out.write("							</div>\r\n");
      out.write("						</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"content-container\">\r\n");
      out.write("				<p id=\"dest_content\">");
      out.print(vo.getDEST_CONTENT());
      out.write("</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/navbar/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		var $likeBtn = $('.icon2.heart2');\r\n");
      out.write("\r\n");
      out.write("		$likeBtn\r\n");
      out.write("				.click(function() {\r\n");
      out.write("					$likeBtn.toggleClass('active');\r\n");
      out.write("\r\n");
      out.write("					if ($likeBtn.hasClass('active')) {\r\n");
      out.write("						$(this)\r\n");
      out.write("								.find('img')\r\n");
      out.write("								.attr(\r\n");
      out.write("										{\r\n");
      out.write("											'src' : 'https://cdn-icons-png.flaticon.com/512/803/803087.png',\r\n");
      out.write("											alt : '찜하기 완료'\r\n");
      out.write("										});\r\n");
      out.write("\r\n");
      out.write("					} else {\r\n");
      out.write("						$(this).find('i').removeClass('fas').addClass('far')\r\n");
      out.write("						$(this)\r\n");
      out.write("								.find('img')\r\n");
      out.write("								.attr(\r\n");
      out.write("										{\r\n");
      out.write("											'src' : 'https://cdn-icons-png.flaticon.com/512/812/812327.png',\r\n");
      out.write("											alt : \"찜하기\"\r\n");
      out.write("										})\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("	})\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
