/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-02-12 10:04:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import net.dest.db.*;

public final class SearchItem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("net.dest.db");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");

Vector<DestVO> list = (Vector<DestVO>) request.getAttribute("destList");
if (list != null) {
	for (int i = 0; i < list.size(); i++) {
		DestVO vo = list.elementAt(i);
		String summary=vo.getDEST_CONTENT();
		if(summary.length()>190){
			summary=summary.substring(0,190);}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"resume-wrap d-flex ftco-animate\">\r\n");
      out.write("	<div class=\"text pl-3\">\r\n");
      out.write("	\r\n");
      out.write("		<!-- 		여행지 이미지 -->\r\n");
      out.write("		<img src=\"");
      out.print(vo.getDEST_IMG());
      out.write("\" class=\"rounded float-start\"\r\n");
      out.write("			alt=\"destimg\" id=\"dest_img\" width=\"400px\">\r\n");
      out.write("			\r\n");
      out.write("		<!-- 클릭시 여행지 상세페이지 -->\r\n");
      out.write("		<form action=\"GetDestDetailView.de\" method=\"post\" id=\"viewForm");
      out.print(vo.getDEST_NAME());
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"dest_name\" value=\"");
      out.print(vo.getDEST_NAME());
      out.write("\">\r\n");
      out.write("			<h2 onclick=\"document.getElementById('viewForm");
      out.print(vo.getDEST_NAME());
      out.write("').submit()\" id=\"dest_select\">\r\n");
      out.write("				<span class=\"rgyBadge\">");
      out.print(vo.getDEST_COUNTRY());
      out.write("</span>&nbsp;<span id=\"dest_name\">");
      out.print(vo.getDEST_NAME());
      out.write("</span>&nbsp;&nbsp;<span\r\n");
      out.write("					class=\"date\" id=\"name_eng\">");
      out.print(vo.getDEST_NAME_ENG());
      out.write("</span>\r\n");
      out.write("			</h2>\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		<div>\r\n");
      out.write("			<span class=\"position\">비용</span>\r\n");
      out.write("			<progress value=\"");
      out.print(vo.getDEST_MONEY() * 100);
      out.write("\" max=\"100\" id=\"pg\"></progress>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<span class=\"position\">경치</span>\r\n");
      out.write("			<progress value=\"");
      out.print(vo.getDEST_LANDSCAPE() * 100);
      out.write("\" max=\"100\" id=\"pg\"></progress>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<span class=\"position\">재미</span>\r\n");
      out.write("			<progress value=\"");
      out.print(vo.getDEST_FUN() * 100);
      out.write("\" max=\"100\" id=\"pg\"></progress>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("		<p id=\"content_preview\">");
      out.print(summary);
      out.write("...</p>\r\n");
      out.write("		\r\n");
      out.write("<!-- 		하트찜 -->\r\n");
      out.write("		<div>\r\n");
      out.write("			<a href=\"javascript:;\" class=\"icon2 heart\">&nbsp;&nbsp;\r\n");
      out.write("				<img src=\"https://cdn-icons-png.flaticon.com/512/812/812327.png\" alt=\"찜하기\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");

}//end for
}//end if

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/aos.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/scrollax.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/main.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function() {\r\n");
      out.write("		var $likeBtn = $('.icon2.heart');\r\n");
      out.write("\r\n");
      out.write("		$likeBtn\r\n");
      out.write("				.click(function() {\r\n");
      out.write("					$likeBtn.toggleClass('active');\r\n");
      out.write("\r\n");
      out.write("					if ($likeBtn.hasClass('active')) {\r\n");
      out.write("						$(this)\r\n");
      out.write("								.find('img')\r\n");
      out.write("								.attr(\r\n");
      out.write("										{\r\n");
      out.write("											'src' : 'https://cdn-icons-png.flaticon.com/512/803/803087.png',\r\n");
      out.write("											alt : '찜하기 완료'\r\n");
      out.write("										});\r\n");
      out.write("\r\n");
      out.write("					} else {\r\n");
      out.write("						$(this).find('i').removeClass('fas').addClass('far')\r\n");
      out.write("						$(this)\r\n");
      out.write("								.find('img')\r\n");
      out.write("								.attr(\r\n");
      out.write("										{\r\n");
      out.write("											'src' : 'https://cdn-icons-png.flaticon.com/512/812/812327.png',\r\n");
      out.write("											alt : \"찜하기\"\r\n");
      out.write("										})\r\n");
      out.write("					}\r\n");
      out.write("				})\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
