CREATE TABLE PROPRAC_NOTICE(
NO1             NUMBER(7)       NOT NULL,
TITLE1          VARCHAR2(200)   NOT NULL,
CONTENT1        VARCHAR2(4000)  NOT NULL,
READCOUNT1      NUMBER(5)       DEFAULT 0 NOT NULL,
REGDATE         TIMESTAMP(6)    DEFAULT SYSDATE NOT NULL,
CONSTRAINT PROPRAC_NOTICE_PK PRIMARY KEY(NO1)
);


INSERT INTO PROPRAC_NOTICE(NO1, TITLE1, CONTENT1, READCOUNT1) VALUES(1, '요기조기이용안내', '글확인', 0);

INSERT INTO PROPRAC_NOTICE(NO1, TITLE1, CONTENT1, READCOUNT1) VALUES(2, '요기조기이용안내', '글확인', 0);

SELECT * FROM PROPRA
C_NOTICE;

DESC PROPRAC_NOTICE;

CREATE SEQUENCE PROPRAC_NOTICE_SEQ
START WITH 2
INCREMENT BY 1
NOMAXVALUE
NOCACHE
NOCYCLE;

INSERT INTO PROPRAC_NOTICE(NO1, TITLE1, CONTENT1, READCOUNT1) VALUES(PROPRAC_NOTICE_SEQ.nextval, '요기조기 회식 일정', '다음주 수요일은 야채곱창입니다. 빠짐없이 참석해 주세요.', 0);
INSERT INTO PROPRAC_NOTICE(NO1, TITLE1, CONTENT1, READCOUNT1) VALUES(PROPRAC_NOTICE_SEQ.nextval, '서비스 이용 안내', '잘 이용해 주세요.', 0);
DROP TABLE PROPRAC_NOTICE;

select * from PROPRAC_NOTICE;
delete from PROPRAC_NOTICE where NO1=3;
COMMIT;