CREATE TABLE PROPRAC (
NO          NUMBER(7)       NOT NULL,
TITLE       VARCHAR2(200)   NOT NULL,
WRITER      VARCHAR2(30)    NOT NULL,
PASS        VARCHAR2(30)    NOT NULL,
CONTENT     VARCHAR2(4000)  NOT NULL,
READCOUNT   NUMBER(5)       DEFAULT 0 NOT NULL,
REF         NUMBER(5)       DEFAULT 0 NOT NULL,
STEP        NUMBER(3)       DEFAULT 0 NOT NULL,
DEPTH       NUMBER(3)       DEFAULT 0 NOT NULL,
REGDATE     TIMESTAMP(6)    DEFAULT SYSDATE NOT NULL,
CONSTRAINT  PROPRAC_PK PRIMARY KEY(NO)
);
DROP TABLE PROPRAC;
SELECT * FROM PROPRAC;
DESC PROPRAC;
COMMIT;

CREATE SEQUENCE PROPRAC_SEQ
START WITH 2
INCREMENT BY 1
NOMAXVALUE
NOCACHE
NOCYCLE;
DROP SEQUENCE PROPRAC_SEQ;
COMMIT;

SELECT * FROM PROPRAC;
INSERT INTO PROPRAC(NO, TITLE, WRITER, PASS, CONTENT, REF, STEP, DEPTH, REGDATE) VALUES(1, '자유롭게 질문해주세요.', '관리자', 'system_master', '안녕하세요. 요기조기 입니다. 자유롭게 질문해주시면 최대한 빠른 시일 내로 답변 드리겠습니다. 감사합니다.', 1, 0, 0, SYSDATE);
DELETE FROM PROPRAC ;
