/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-02-12 14:49:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Search_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

int money_pri=0;
int land_pri=0;
int fun_pri=0;
if(request.getAttribute("money_pri")!=null&&request.getAttribute("land_pri")!=null&&request.getAttribute("fun_pri")!=null){
	money_pri=(int)request.getAttribute("money_pri");
	land_pri=(int)request.getAttribute("land_pri");
	fun_pri=(int)request.getAttribute("fun_pri");
}



      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/search_main.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style2.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<title>여행지 조회</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\"\r\n");
      out.write("	data-offset=\"300\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/navbar/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<span class=\"search_head\">키워드로 검색</span>&nbsp;\r\n");
      out.write("\r\n");
      out.write("		<form action=\"GetDestinationList.de\" method=\"post\" class=\"search_form\">\r\n");
      out.write("			<input class=\"form-control\" type=\"text\" name=\"keyword\"\r\n");
      out.write("				placeholder=\"검색어 입력\" aria-label=\"default input example\"\r\n");
      out.write("				style=\"width: 75%; display: inline;\"> &nbsp; <input\r\n");
      out.write("				class=\"btn btn-outline-dark\" type=\"submit\" id=\"button-addon2\"\r\n");
      out.write("				 value=\"검색\">\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<br> <span class=\"search_head\">우선순위로 검색&nbsp;<span\r\n");
      out.write("			class=\"tooltip_custom\">?<span class=\"tooltip-content_custom\">각\r\n");
      out.write("					속성의 우선순위에 따라 가중치를 반영하여 검색합니다. </span></span></span> <br>\r\n");
      out.write("					\r\n");
      out.write("		<form action=\"GetPriorityList.de\" method=\"get\" class=\"search_form\">\r\n");
      out.write("			<span class=\"search_sub\">비용</span> <select class=\"form-select\"\r\n");
      out.write("				name=\"money\" style=\"width: auto; display: inline;\">\r\n");
      out.write("				<option ");
if(money_pri==0){ 
      out.write("selected=\"selected\"");
} 
      out.write(">-</option>\r\n");
      out.write("				<option value=\"1\" ");
if(money_pri==1){ 
      out.write(" selected=\"selected\"");
} 
      out.write(">1순위</option>\r\n");
      out.write("				<option value=\"2\" ");
if(money_pri==2){ 
      out.write("selected=\"selected\"");
} 
      out.write(">2순위</option>\r\n");
      out.write("				<option value=\"3\" ");
if(money_pri==3){ 
      out.write("selected=\"selected\"");
} 
      out.write(">3순위</option>\r\n");
      out.write("			</select> <span class=\"search_sub\">경치</span> <select class=\"form-select\"\r\n");
      out.write("				name=\"landscape\" style=\"width: auto; display: inline;\">\r\n");
      out.write("				<option ");
if(land_pri==0){ 
      out.write("selected=\"selected\"");
} 
      out.write(">-</option>\r\n");
      out.write("				<option value=\"1\" ");
if(land_pri==1){ 
      out.write(" selected=\"selected\"");
} 
      out.write(">1순위</option>\r\n");
      out.write("				<option value=\"2\" ");
if(land_pri==2){ 
      out.write("selected=\"selected\"");
} 
      out.write(">2순위</option>\r\n");
      out.write("				<option value=\"3\" ");
if(land_pri==3){ 
      out.write("selected=\"selected\"");
} 
      out.write(">3순위</option>\r\n");
      out.write("			</select> <span class=\"search_sub\">재미</span> <select class=\"form-select\"\r\n");
      out.write("				name=\"fun\" style=\"width: auto; display: inline;\">\r\n");
      out.write("				<option ");
if(fun_pri==0){ 
      out.write("selected=\"selected\"");
} 
      out.write(">-</option>\r\n");
      out.write("				<option value=\"1\" ");
if(fun_pri==1){ 
      out.write(" selected=\"selected\"");
} 
      out.write(">1순위</option>\r\n");
      out.write("				<option value=\"2\" ");
if(fun_pri==2){ 
      out.write("selected=\"selected\"");
} 
      out.write(">2순위</option>\r\n");
      out.write("				<option value=\"3\" ");
if(fun_pri==3){ 
      out.write("selected=\"selected\"");
} 
      out.write(">3순위</option>\r\n");
      out.write("			</select> &nbsp;\r\n");
      out.write("			<button class=\"btn btn-outline-dark\" type=\"submit\"\r\n");
      out.write("				>검색</button>\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("		<br> <span class=\"search_head\">나만의 추천 여행지 리스트!&nbsp;<span\r\n");
      out.write("			class=\"tooltip_custom\">?<span class=\"tooltip-content_custom\">각\r\n");
      out.write("					속성의 우선순위에 따라 가중치를 반영하여 검색합니다. </span></span></span> <br>\r\n");
      out.write("		<form action=\"RecommandList.de\" method=\"get\" class=\"search_form\">\r\n");
      out.write("			<button class=\"btn btn-outline-dark\" type=\"submit\">추천 리스트 보기</button>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h2 class=\"heading\">Tourist Attractions</h2>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/search/SearchItem.jsp", out, false);
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("	<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("		<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" />\r\n");
      out.write("		</svg>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/navbar/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
